

services:

  postgres:
    image: postgres:15
    container_name: agent_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: agentdb
    ports:
      - "5432:5432"
    volumes:
      - ./infrastructure/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_db
    ports:
      - "6333:6333"
      - "6334:6334"
    restart: always

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: agent_api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - qdrant
    restart: always
